name: Create Trello card on opened issues

on:
  issues:
    types: [labeled]

jobs:
  create_trello_card_job:
    if: github.event.label.name == 'important'
    runs-on: ubuntu-latest
    name: Create Trello Card
    steps:
      - name: Call trello-github-actions
        uses: LiangRenDev/github-action-trello-integration@main
        with:
          action: issue_opened_create_card
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          # TRELLO_BOARD_ID must match a board. GH repo should connect
          # to exactly one board, but Trello board may connect to multiple
          # GH repositories.
          TRELLO_BOARD_ID: 63f5408209d90add69566672
          # Backlog list ID
          TRELLO_LIST_ID: 63f54125ac72b4962e2549b2
          TRELLO_ACTION_VERBOSE: true
          TRELLO_API_DEBUG: true
          GITHUB_API_DEBUG: true
